### ISSUE TITLE
Mise en place d'une transmission automatique des commits GitLab

### ISSUE THREAD

**Issue by Sacha-N** [Sacha-N/Trajectoires-dans-la-FP#6]
@Sacha-N, suivre cette démarche : 

You can set up a GitLab CI/CD pipeline to push changes to GitHub every time you commit to GitLab.
Steps

1. Create a Personal Access Token (PAT) on GitHub

- Go to GitHub → Settings → Developer settings → Personal Access Tokens.
- Generate a new token with repo scope.
- Copy the token for later use.

2. Add the GitHub Token to GitLab

- In your GitLab project, go to Settings → CI/CD → Variables.
- Add a new variable :  Key: GITHUB_TOKEN, Value: <your_github_token>

3. Add .gitlab-ci.yml Add this file in your GitLab repository to push changes to GitHub:

```
stages:
  - sync

sync_with_github:
  stage: sync
  script:
    - git config --global user.email "your-email@example.com"
    - git config --global user.name "Your Name"
    - git remote add github https://your-github-username:${GITHUB_TOKEN}@github.com/your-github-username/your-repo.git
    - git push --mirror github
  only:
    - main  # Adjust the branch if needed
```

4. Commit & Push

- Push your changes to GitLab, and the pipeline will sync them to GitHub.
